#!/usr/bin/env node

//----------------------------------------------------------------------------
// Help Description
//----------------------------------------------------------------------------
var HELP_DESCRIPTION='No help available.';
var HELP_VERBOSE='No verbose help is available.';

if (process.argv.length === 3 && process.argv[2] == '--help') {
  console.log(HELP_DESCRIPTION);
  process.exit(0);
}
if (process.argv.length === 4 && process.argv[2] == '--help' && process.argv[3] == '--verbose') {
  console.log(HELP_VERBOSE);
  process.exit(0);
}

//----------------------------------------------------------------------------
// Command code goes here...
//----------------------------------------------------------------------------
console.log('Example node command');

// Below will exit with a failure code to break a build
//process.exit(1);