#!/bin/bash
# This is the parent build script
# It takes the subcommand and sends it to a script with the same name

#---------------------------------------
# Save where the build is installed
#---------------------------------------
export BUILDDIR=/usr/local/lib/jsonxr-build
export DOTDIR=~/.b

#---------------------------------------
# Find the project directory looking for
# the ".git" directory
#---------------------------------------
CURRENT=$(pwd)
while [ ! -d $CURRENT/.git ]; do
  if [ "$CURRENT" == "/" ]; then
    break
  fi
  CURRENT="$(dirname "$CURRENT")"
done
if [ -d $CURRENT/.git ]; then
  export PROJECTDIR=$CURRENT
else
  echo "Don't know where project is because the '.git' folder can not be found."
  exit 1
fi

#---------------------------------------
# Get the command from the arguments, help is default
#---------------------------------------
if [ "$1" == "" ]; then
  CMD='help'
else
  CMD=$1
fi


#---------------------------------------
# execute cmd in the following order:  project, dotdir, the commands dir
#---------------------------------------
if [ -f $PROJECTDIR/bin/$CMD ]; then
  $PROJECTDIR/bin/$CMD $2 $3 $4 $5 $6 $7 $8 $9
elif [ -f $DOTDIR/$CMD ]; then
  $DOTDIR/$CMD $2 $3 $4 $5 $6 $7 $8 $9
elif [ -f $BUILDDIR/commands/$CMD ]; then
  $BUILDDIR/commands/$CMD $2 $3 $4 $5 $6 $7 $8 $9
else
  echo "build: command '$CMD' not found in"
  echo "    $PROJECTDIR"
  echo "    $DOTDIR"
  echo "    $BUILDDIR"
fi

