#!/bin/bash

#-----------------------------------------------------------------------------
# Help Description
#-----------------------------------------------------------------------------
if [ "$1" == "--help" ]; then
  # No help available, don't even show this command
  exit
fi


#-----------------------------------------------------------------------------
# Command
#-----------------------------------------------------------------------------

DOCKERCOMPOSE=$(which docker-compose)
if [ "$DOCKERCOMPOSE" == "" ]; then
  echo 
  echo "installing docker-compose..."
  echo "----------------------------"
  DOWNLOAD=https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m`
  curl -L $DOWNLOAD > /usr/local/bin/docker-compose
  chmod +x /usr/local/bin/docker-compose
  DOCKERCOMPOSE=$(which docker-compose)
fi

echo "$DOCKERCOMPOSE"
